name: CI
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      
      - name: Install packages and run lint
        run: |
          cd ui
          npm install
          npm lint
