name: CI
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: ui
        run: npm install

      - name: Lint
        working-directory: ui
        run: npm run lint

      - name: Build
        working-directory: ui
        run: npm run build
